# Generated by Django 4.2.24 on 2025-11-12 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0002_pipeline_finished_on'),
        ('watermarks', '0009_migrate_old_pipelines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='regions_task',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='similarity_task',
        ),
        migrations.DeleteModel(
            name='Pipeline',
        ),
    ]
