# Generated by Django 4.2.24 on 2025-11-12 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0002_pipeline_finished_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='regions_task',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='similarity_task',
        ),
    ]
