# Generated by Django 4.2.24 on 2025-11-12 17:21

from django.db import migrations, models
import django.db.models.deletion

# migrate old Pipelines to new WatermarksPipeline
def migrate_pipelines(apps, schema_editor):
    Pipeline = apps.get_model('pipelines', 'Pipeline')
    WatermarksPipeline = apps.get_model('watermarks', 'WatermarksPipeline')
    for pipeline in Pipeline.objects.all():
        WatermarksPipeline.objects.create(
            analysis_type="similarity",
            need_regions=True,
            indexing_task=None,
            query_target_index=None,
            query_task=None,
            regions_task=pipeline.regions_task,
            similarity_task=pipeline.similarity_task,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0007_remove_regions_pipeline'),
        ('search', '0002_remove_indexing_pipeline_remove_query_pipeline_and_more'),
        ('pipelines', '0003_remove_pipeline_regions_task_and_more'),
        ('similarity', '0005_remove_similarity_pipeline'),
        ('watermarks', '0007_watermarkprocessing_finished_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatermarksPipeline',
            fields=[
                ('pipeline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipelines.pipeline')),
                ('analysis_type', models.CharField(choices=[('similarity', 'Compare watermarks inside dataset'), ('indexing', 'Index this dataset for future queries'), ('query', 'Search inside an indexed dataset')], default='similarity', max_length=10, verbose_name='Analysis type')),
                ('need_regions', models.BooleanField(blank=True, default=True, help_text='Disable if your images are already cropped', verbose_name='Detect and crop watermarks')),
                ('indexing_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='search.indexing', verbose_name='Indexing task')),
                ('query_target_index', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='search.index', verbose_name='Query target index')),
                ('query_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='search.query', verbose_name='Query task')),
                ('regions_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='regions.regions', verbose_name='Watermarks detection task')),
                ('similarity_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='similarity.similarity', verbose_name='Watermarks similarity task')),
            ],
            options={
                'ordering': ['-requested_on'],
                'abstract': False,
            },
            bases=('pipelines.pipeline',),
        ),
        migrations.RunPython(migrate_pipelines, reverse_code=migrations.RunPython.noop),
        migrations.DeleteModel(
            name='WatermarkProcessing',
        ),
        migrations.DeleteModel(
            name='WatermarksSource',
        ),
    ]
