# Generated by Django 4.2.24 on 2025-11-12 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid

# migrate old Pipelines to new WatermarksPipeline
def migrate_pipelines(apps, schema_editor):
    Pipeline = apps.get_model('pipelines', 'Pipeline')
    WatermarksPipeline = apps.get_model('watermarks', 'WatermarksPipeline')
    Regions = apps.get_model('regions', 'Regions')
    Similarity = apps.get_model('similarity', 'Similarity')
    for pipeline in Pipeline.objects.all():
        regions_task_id = pipeline.regions_task_id
        similarity_task_id = pipeline.similarity_task_id

        try:
            regions_task = Regions.objects.get(pk=regions_task_id)
        except Regions.DoesNotExist:
            regions_task = None

        try:
            similarity_task = Similarity.objects.get(pk=similarity_task_id)
        except Similarity.DoesNotExist:
            similarity_task = None
        
        new_pipeline = WatermarksPipeline.objects.create(
            analysis_type="similarity",
            need_regions=True,
            indexing_task=None,
            query_target_index=None,
            query_task=None,
            regions_task_id=regions_task_id,
            similarity_task_id=similarity_task_id,
            dataset_id=pipeline.dataset_id,
            requested_by_id=pipeline.requested_by_id,
            notify_email=pipeline.notify_email,
            status=pipeline.status,
            is_finished=pipeline.is_finished,
            requested_on=pipeline.requested_on,
            finished_on=pipeline.finished_on,
            parameters=pipeline.parameters,
            name=pipeline.name,
        )
        new_pipeline.requested_on = pipeline.requested_on
        new_pipeline.finished_on = pipeline.finished_on
        new_pipeline.save(update_fields=["requested_on", "finished_on"])

        if regions_task:
            regions_task.watermarks_pipeline = new_pipeline
            regions_task.save()
        if similarity_task:
            similarity_task.watermarks_pipeline = new_pipeline
            similarity_task.save()

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watermarks', '0008_watermarkspipelines'),
        ('regions', '0007_watermarkspipelines'),
        ('similarity', '0005_watermarkspipelines'),
        ('dticlustering', '0013_watermarkspipelines'),
        ('search', '0003_watermarkspipelines'),
        ('pipelines', '0002_pipeline_finished_on'),
    ]

    operations = [
        migrations.RunPython(migrate_pipelines),
        migrations.DeleteModel(
            name='WatermarkProcessing',
        ),
        migrations.DeleteModel(
            name='WatermarksSource',
        ),
    ]
