# Generated by Django migration for Alignment app

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("regions", "0004_remove_regions_model_alter_regions_dataset"),
        ("datasets", "0005_delete_zippeddataset_remove_dataset_format_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional name to identify this alignment experiment",
                        max_length=64,
                        verbose_name="Experiment name",
                    ),
                ),
                (
                    "notify_email",
                    models.BooleanField(
                        blank=True,
                        default=True,
                        help_text="Send an email when the alignment task is finished",
                        verbose_name="Notify by email",
                    ),
                ),
                (
                    "status",
                    models.CharField(default="PENDING", editable=False, max_length=20),
                ),
                ("is_finished", models.BooleanField(default=False, editable=False)),
                ("requested_on", models.DateTimeField(auto_now_add=True)),
                ("api_tracking_id", models.UUIDField(editable=False, null=True)),
                ("parameters", models.JSONField(null=True)),
                (
                    "crops",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alignment_crops",
                        to="regions.regions",
                        verbose_name="Use crops from...",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alignment_tasks",
                        to="datasets.dataset",
                        verbose_name="Use existing dataset...",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
