# Generated by Django 4.2.24 on 2025-11-12 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0006_regions_finished_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regions',
            name='pipeline',
        ),
    ]
