# Generated by Django 4.2.24 on 2025-11-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexing',
            name='pipeline',
        ),
        migrations.RemoveField(
            model_name='query',
            name='pipeline',
        ),
        migrations.AddField(
            model_name='index',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='index',
            name='feat_net',
            field=models.CharField(blank=True, default='', max_length=511),
        ),
    ]
