# Generated by Django 4.2.24 on 2025-11-12 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_index_fields'),
        ('watermarks', '0008_watermarkspipelines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexing',
            name='pipeline',
        ),
        migrations.RemoveField(
            model_name='query',
            name='pipeline',
        ),
        migrations.AddField(
            model_name='indexing',
            name='watermarks_pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='watermarks.watermarkspipeline'),
        ),
        migrations.AddField(
            model_name='query',
            name='watermarks_pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='watermarks.watermarkspipeline'),
        ),
    ]
