# Generated by Django 4.2.24 on 2025-11-12 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_remove_indexing_pipeline_remove_query_pipeline_and_more'),
        ('watermarks', '0008_watermarkspipeline_delete_watermarkprocessing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexing',
            name='watermarks_pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_indexing_tasks', to='watermarks.watermarkspipeline'),
        ),
        migrations.AddField(
            model_name='query',
            name='watermarks_pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_query_tasks', to='watermarks.watermarkspipeline'),
        ),
    ]
