# Generated by Django 4.2.30 on 2026-06-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_watermarkspipelines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=511, unique=True),
        ),
    ]
