# Generated by Django 4.2.24 on 2025-10-23 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0006_regions_finished_on'),
        ('similarity', '0003_similarity_finished_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similarity',
            name='crops',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='regions.regions', verbose_name='Use crops from...'),
        ),
    ]
