# Generated by Django 4.2.24 on 2025-11-12 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('similarity', '0004_alter_similarity_crops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='similarity',
            name='pipeline',
        ),
    ]
