# Generated by Django 4.2.24 on 2025-11-12 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('similarity', '0005_remove_similarity_pipeline'),
        ('watermarks', '0008_watermarkspipeline_delete_watermarkprocessing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='similarity',
            name='watermarks_pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similarity_tasks', to='watermarks.watermarkspipeline'),
        ),
    ]
