# Generated by Django 4.2.20 on 2025-10-11 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0006_regions_finished_on"),
        ("dticlustering", "0010_dticlustering_finished_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="dticlustering",
            name="crops",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dticlustering_crops",
                to="regions.regions",
                verbose_name="Use crops from...",
            ),
        ),
    ]
