# Generated by Django 4.2.24 on 2025-11-10 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0006_regions_finished_on'),
        ('dticlustering', '0011_dticlustering_crops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dticlustering',
            name='crops',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='regions.regions', verbose_name='Use crops from...'),
        ),
    ]
