# Generated by Django 4.2.24 on 2025-11-12 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watermarks', '0008_watermarkspipeline_delete_watermarkprocessing_and_more'),
        ('dticlustering', '0012_alter_dticlustering_crops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dticlustering',
            name='pipeline',
        ),
        migrations.AddField(
            model_name='dticlustering',
            name='watermarks_pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dticlustering_tasks', to='watermarks.watermarkspipeline'),
        ),
    ]
